### PR TITLE
Make it clearer that chair and supervisor variables are required

### PR DESCRIPTION
**Pull request by rbottema**

### CODE REVIEW

**Comment by Inventitech** [comment]
I am happy to merge this, but the current way of referring to the person should stay there as an example, for uniformity.

**Comment by rbottema** [comment]
The thesis.tex already contains example content (lines 82 and 83), is that what you mean? The change here is simply in the default value when none are explicitly specified, which could lead to confusion when the commands are (accidentally) removed from thesis.tex.

**Comment by Inventitech** [comment]
Yes! In thesis.tex, could you add a `% CHANGE TO YOUR COMMITTEE` comment in the same style that appears above in that document? Also, how about filling the default variables in the sty with this string, i.e. `DEFINE \variable`, for consistency and increased awareness?

**Comment by rbottema** [comment]
I added your first suggestion, but I'm not sure what you mean with your second suggestion. Could you elaborate?

**Comment by Inventitech** [comment]
What about something like `\gdef\@chair{please define \texttt{\textbackslash{}chair}}`?

**Pull request closed without merging**
