### PR TITLE
Add example for specifying research questions

### PR DESCRIPTION
**Pull request by TimvdLippe**
Using the package `enumitem` we can standardize the way research questions are shown:
image

### CODE REVIEW

**Comment by Inventitech** [comment]
Hmm ... often, a thesis revolves around one research question that is then redefined into multiple goals later.

**Comment by TimvdLippe** [comment]
@Inventitech I made these changes based on the format of Niels Spruit and Bastiaan van Graafeiland their theses, which both define multiple research questions from the get-go in the introduction.

**Comment by TimvdLippe** [comment]
Friendly ping 😄

**Comment by Inventitech** [comment]
Closing this.

**Pull request closed without merging**
